#!/bin/sh
# SnipVault sync server — one-command installer.
#
# Stands up the prebuilt server image from GitHub Container Registry with a
# freshly generated token and a persistent data volume — no git clone, no build.
#
#   curl -fsSL https://raw.githubusercontent.com/FranciszekRyszka/Snippet-Vault/main/install.sh | sh
#
# or download it first and run `sh install.sh`. Re-running is safe: it keeps the
# existing token and data, and just pulls the latest image and restarts.
#
# Environment knobs (all optional):
#   SNIPVAULT_DIR    install directory            (default: ./snipvault)
#   SNIPVAULT_PORT   host port to expose          (default: 3000)
#   SNIPVAULT_TOKEN  use this token instead of a generated one
set -eu

DIR="${SNIPVAULT_DIR:-snipvault}"
PORT="${SNIPVAULT_PORT:-3000}"
IMAGE="ghcr.io/franciszekryszka/snippet-vault:latest"

say() { printf '%s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- Preconditions ---------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/engine/install/"

# Prefer the Compose v2 plugin (`docker compose`); fall back to legacy
# `docker-compose` if that's what's present.
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "Docker Compose is not available. Install the Compose plugin: https://docs.docker.com/compose/install/"
fi

# --- Token: reuse an existing one, else generate a strong random token -----
mkdir -p "$DIR"
cd "$DIR"

existing_token=""
if [ -f .env ]; then
  existing_token=$(sed -n 's/^SNIPVAULT_TOKEN=//p' .env | head -n1)
fi

if [ -n "${SNIPVAULT_TOKEN:-}" ]; then
  TOKEN="$SNIPVAULT_TOKEN"
elif [ -n "$existing_token" ]; then
  TOKEN="$existing_token"
elif command -v openssl >/dev/null 2>&1; then
  TOKEN=$(openssl rand -base64 32 | tr -d '\n')
else
  # Fallback if openssl isn't present: hex from the kernel RNG.
  TOKEN=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
fi
[ -n "$TOKEN" ] || die "could not obtain a token"

# --- Write .env and a self-contained compose file --------------------------
umask 077
cat > .env <<EOF
# Generated by install.sh. Keep this file private — the token grants full access.
SNIPVAULT_TOKEN=$TOKEN
SNIPVAULT_PORT=$PORT
EOF
umask 022

cat > docker-compose.yml <<'EOF'
# SnipVault sync server (generated by install.sh). Uses the prebuilt image and a
# named volume so your library survives restarts and image updates. To add
# HTTPS, multiple users, or backups, see docs/self-hosting.md in the repo.
services:
  snipvault:
    image: ghcr.io/franciszekryszka/snippet-vault:latest
    container_name: snipvault
    restart: unless-stopped
    ports:
      - "${SNIPVAULT_PORT:-3000}:3000"
    environment:
      SNIPVAULT_TOKEN: ${SNIPVAULT_TOKEN:-}
    volumes:
      - snipvault-data:/app/data
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:3000/api/health',{headers:{Authorization:'Bearer '+(process.env.SNIPVAULT_TOKEN||'')}}).then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  snipvault-data:
EOF

# --- Pull and start --------------------------------------------------------
say "Pulling the latest image…"
docker pull "$IMAGE" >/dev/null

say "Starting SnipVault…"
# shellcheck disable=SC2086
$COMPOSE up -d

# --- Report ----------------------------------------------------------------
host=$(hostname -I 2>/dev/null | awk '{print $1}')
[ -n "$host" ] || host="<this-host>"

say ""
say "SnipVault is up."
say "  URL:   http://$host:$PORT"
say "  Token: $TOKEN"
say ""
say "In the desktop app: Settings → Sync server → enter that URL and token."
say "Config lives in: $(pwd) (.env + docker-compose.yml)."
say "Stop with: $COMPOSE down   ·   Update with: re-run this script."
